<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_636c9ac60758d',
	'title' => 'Popup Inhalt',
	'fields' => array(
		array(
			'key' => 'field_6372066d76171',
			'label' => 'Anzeigebedingungen',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'wpml_cf_preferences' => 1,
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_637206c317cbf',
			'label' => 'Popup aktivieren',
			'name' => 'nts_pop_active',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Popup aktivieren',
			'default_value' => 1,
			'ui_on_text' => 'Aktiv',
			'ui_off_text' => 'Inaktiv',
			'ui' => 1,
		),
		array(
			'key' => 'field_65a8fce280505',
			'label' => 'Auf der kompletten Website anzeigen',
			'name' => 'nts_pop_show_everywhere',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'ui' => 1,
			'message' => '',
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_65a8fcfd80506',
			'label' => 'Seiten / Beiträge auswählen, auf denen das Popup sichtbar sein soll (Mehrfachauswahl möglich)',
			'name' => 'nts_pop_visibility',
			'aria-label' => '',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_65a8fce280505',
						'operator' => '!=',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'multiple' => 1,
			'ui' => 1,
			'post_type' => array(
			),
			'taxonomy' => array(
			),
			'allow_null' => 0,
			'bidirectional_target' => array(
			),
		),
		array(
			'key' => 'field_636c9ac61d192',
			'label' => 'Veröffentlichungszeitraum',
			'name' => 'nts_pop_timeframe',
			'aria-label' => '',
			'type' => 'group',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_636c9ac65fcea',
					'label' => 'Aktiv von',
					'name' => 'nts_pop_start_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd. F Y',
					'return_format' => 'Y-m-d',
					'first_day' => 1,
				),
				array(
					'key' => 'field_636c9ac65fcf6',
					'label' => 'Aktiv bis',
					'name' => 'nts_pop_end_date',
					'aria-label' => '',
					'type' => 'date_picker',
					'instructions' => '',
					'required' => false,
					'conditional_logic' => false,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd. F Y',
					'return_format' => 'Y-m-d',
					'first_day' => 1,
				),
			),
		),
		array(
			'key' => 'field_66308124a1ad3',
			'label' => 'Aussehen',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_6630813da1ad4',
			'label' => 'Stil',
			'name' => 'nts_pop_style',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'default' => 'Pop Up',
				'fly-in' => 'Fly In',
				'bottom-bar' => 'Sticky Bar',
			),
			'default_value' => 'default',
			'layout' => 'vertical',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_6630823da1ad5',
			'label' => 'Verhalten',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
			'selected' => 0,
		),
		array(
			'key' => 'field_66308270a1ad6',
			'label' => 'Wann soll das Popup erscheinen?',
			'name' => 'nts_pop_trigger',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => false,
			'conditional_logic' => false,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'time-delay' => 'Zeitgesteuert',
				'scroll-amount' => 'Beim Scrollen der Seite',
				'click' => 'Beim Klick auf ein Element (Link, Button, etc.)',
				'element-visible' => 'Sobald ein bestimmtes Element sichtbar wird (z.B. Sprunganker)',
			),
			'default_value' => 'time-delay',
			'layout' => 'vertical',
			'other_choice' => 0,
			'save_other_choice' => 0,
			'allow_null' => 0,
			'return_format' => 'value',
		),
		array(
			'key' => 'field_663083c8a1ad7',
			'label' => 'Popup nach X Sekunden anzeigen',
			'name' => 'nts_pop_time_delay',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66308270a1ad6',
						'operator' => '==',
						'value' => 'time-delay',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 1,
			'min' => '',
			'max' => '',
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66308440a1ad8',
			'label' => 'Popup nach x Prozent Website-Scroll anzeigen',
			'name' => 'nts_pop_scroll_amount',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66308270a1ad6',
						'operator' => '==',
						'value' => 'scroll-amount',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 20,
			'min' => 0,
			'max' => 100,
			'step' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_663084ada1ad9',
			'label' => 'CSS-Klasse oder ID des zu klickenden Elements angeben',
			'name' => 'nts_pop_clicked_element',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie die CSS-Klassen und/oder IDs der entsprechenden Elemente, als Komma getrennte Liste, an, inklusive dem voranstehenden . oder #',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66308270a1ad6',
						'operator' => '==',
						'value' => 'click',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_66308542a1ada',
			'label' => 'CSS-ID des Elements, welches, wenn sichtbar, das Popup auslösen soll',
			'name' => 'nts_pop_visible_element_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Geben Sie die CSS-ID des entsprechenden Elements an, inklusive dem voranstehenden #',
			'required' => 1,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_66308270a1ad6',
						'operator' => '==',
						'value' => 'element-visible',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6718c509baba6',
			'label' => 'Merken',
			'name' => 'nos_popup_storage',
			'aria-label' => '',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'session' => 'Für die aktive Sitzung merken',
				'local' => 'Für immer merken',
				'none' => 'Nicht merken',
			),
			'default_value' => 'session',
			'return_format' => 'value',
			'multiple' => 0,
			'allow_null' => 0,
			'allow_in_bindings' => 0,
			'ui' => 0,
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6718beae6a299',
			'label' => 'Inhalte',
			'name' => '',
			'aria-label' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 1,
			'selected' => 0,
		),
		array(
			'key' => 'field_6718e47096f2f',
			'label' => 'Textfarbe',
			'name' => 'nos_popup_content_sticky_bar_text_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6630813da1ad4',
						'operator' => '==',
						'value' => 'bottom-bar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6718e44d96f2e',
			'label' => 'Hintergrundfarbe',
			'name' => 'nos_popup_content_sticky_bar_bg_color',
			'aria-label' => '',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6630813da1ad4',
						'operator' => '==',
						'value' => 'bottom-bar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '#ffffff',
			'enable_opacity' => 0,
			'return_format' => 'string',
			'allow_in_bindings' => 0,
		),
		array(
			'key' => 'field_6718c13670869',
			'label' => 'Text',
			'name' => 'nos_popup_content_sticky_bar_text',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6630813da1ad4',
						'operator' => '==',
						'value' => 'bottom-bar',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'allow_in_bindings' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
		array(
			'key' => 'field_6718bc976a297',
			'label' => 'Inhaltselemente (Fly In)',
			'name' => 'nos_popup_contents_fly_in',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6630813da1ad4',
						'operator' => '==',
						'value' => 'fly-in',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_6718c0a23e04f' => array(
					'key' => 'layout_6718c0a23e04f',
					'name' => 'nos_popup_layout_text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6718c509baba5',
							'label' => 'Innenabstand Textspalte',
							'name' => 'nos_popup_layout_text_innenabstand_textspalte',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'l' => 'Groß',
								'm' => 'Mittel',
								's' => 'Klein',
								'none' => 'Kein Innenabstand',
							),
							'default_value' => 'm',
							'return_format' => 'value',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_6718c1a97086a',
							'label' => 'Text eingeben',
							'name' => 'nos_popup_layout_text_text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6718c300bab9f' => array(
					'key' => 'layout_6718c300bab9f',
					'name' => 'nos_popup_layout_image',
					'label' => 'Bild',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6718c300baba0',
							'label' => 'Bild auswählen',
							'name' => 'nos_popup_layout_image_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Layout hinzufügen',
		),
		array(
			'key' => 'field_6718d156b85c9',
			'label' => 'Inhaltselemente (Pop Up)',
			'name' => 'nos_popup_contents_pop_up',
			'aria-label' => '',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6630813da1ad4',
						'operator' => '==',
						'value' => 'default',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_6718c0a23e04f' => array(
					'key' => 'layout_6718c0a23e04f',
					'name' => 'nos_popup_layout_text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6718d156b85ca',
							'label' => 'Innenabstand Textspalte',
							'name' => 'nos_popup_layout_text_innenabstand_textspalte',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'l' => 'Groß',
								'm' => 'Mittel',
								's' => 'Klein',
								'none' => 'Kein Innenabstand',
							),
							'default_value' => 'm',
							'return_format' => '',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_6718d156b85cb',
							'label' => 'Text eingeben',
							'name' => 'nos_popup_layout_text_text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6718c300bab9f' => array(
					'key' => 'layout_6718c300bab9f',
					'name' => 'nos_popup_layout_image',
					'label' => 'Bild',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_6718d156b85cc',
							'label' => 'Bild auswählen',
							'name' => 'nos_popup_layout_image_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => '',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_6718c3f3baba2' => array(
					'key' => 'layout_6718c3f3baba2',
					'name' => 'nos_popup_layout_image_text',
					'label' => 'Bild & Text nebeneinander',
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_6718d156b85cd',
							'label' => 'Spaltengrößen',
							'name' => 'nos_popup_layout_colsizes',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'img-1-4-text-3-4' => 'Bild 1/4 Text 3/4',
								'img-1-3-text-2-3' => 'Bild 1/3 Text 2/3',
								'img-1-2-text-1-2' => 'Bild 1/2 Text 1/2',
								'img-2-3-text-1-3' => 'Bild 2/3 Text 1/3',
								'img-3-4-text-1-4' => 'Bild 3/4 Text 1/4',
							),
							'default_value' => 'img-1-2-text-1-2',
							'return_format' => '',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_6718eda3adb11',
							'label' => 'Positionierung',
							'name' => 'nos_popup_layout_image_text_positionierung',
							'aria-label' => '',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'image-left' => 'Bild links, Text rechts',
								'image-right' => 'Text links, Bild rechts',
							),
							'default_value' => 'image-left',
							'return_format' => 'value',
							'allow_null' => 0,
							'other_choice' => 0,
							'allow_in_bindings' => 0,
							'layout' => 'vertical',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_6718d156b85ce',
							'label' => 'Bild auswählen',
							'name' => 'nos_popup_layout_image_text_image',
							'aria-label' => '',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => '',
							'library' => '',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
							'allow_in_bindings' => 0,
							'preview_size' => 'medium',
						),
						array(
							'key' => 'field_6718d156b85cf',
							'label' => 'Innenabstand Textspalte',
							'name' => 'nos_popup_layout_image_text_innenabstand_textspalte',
							'aria-label' => '',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'l' => 'Groß',
								'm' => 'Mittel',
								's' => 'Klein',
								'none' => 'Kein Innenabstand',
							),
							'default_value' => 'm',
							'return_format' => '',
							'multiple' => 0,
							'allow_null' => 0,
							'allow_in_bindings' => 0,
							'ui' => 0,
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_6718d156b85d0',
							'label' => 'Text eingeben',
							'name' => 'nos_popup_layout_image_text_text',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'allow_in_bindings' => 0,
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'min' => '',
			'max' => '',
			'button_label' => 'Layout hinzufügen',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'nos_popups',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'discussion',
		3 => 'comments',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );